name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI (${{ matrix.toolchain }})
    runs-on: ubuntu-*
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      matrix:
        include:
          - toolchain: stable
            allow_failure: false
          - toolchain: nightly
            allow_failure: true

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (${{ matrix.toolchain }})
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - name: Cache cargo registry + build
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

      - name: Tests
        run: cargo test --all-features
